# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):

    obj = bld.create_ns3_program('vndn-example-beacon', ['ndn4ivc'])
    obj.source = 'vndn-example-beacon.cc'

    obj = bld.create_ns3_program('vndn-example-beacon-grid', ['ndn4ivc'])
    obj.source = 'vndn-example-beacon-grid.cc'

    obj = bld.create_ns3_program('vndn-sumo-circle', ['ndn4ivc'])
    obj.source = 'vndn-sumo-circle.cc'